package com.samapp.renttrack.data.repository

import android.content.Context
import android.content.Intent
import android.content.SharedPreferences
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.os.Environment
import android.util.Log
import androidx.core.content.FileProvider
import com.samapp.renttrack.data.local.model.Tenant
import com.samapp.renttrack.domain.repositories.invoice.RentInvoiceRepository
import java.io.File
import java.io.FileOutputStream
import java.io.IOException
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class RentInvoiceRepositoryImpl(private val context: Context) : RentInvoiceRepository {
    private val sharedPreferences: SharedPreferences =
        context.getSharedPreferences("RentTrackPrefs", Context.MODE_PRIVATE)

    private fun getNextReceiptNumber(): Int {
        val lastNumber = sharedPreferences.getInt("last_receipt_number", 999)
        val newNumber = lastNumber + 1
        sharedPreferences.edit().putInt("last_receipt_number", newNumber).apply()
        return newNumber
    }
    override suspend fun generateInvoice(tenant: Tenant,amount: String, rentDate: String): File? {
        Log.d("Invoice", "Generating invoice for ${tenant.name} with amount ₹$amount on $rentDate")

        val receiptNumber = getNextReceiptNumber()
        val formattedDate = SimpleDateFormat("yyyyMMdd", Locale.getDefault()).format(Date())
        val fileName = "${tenant.name}_${formattedDate}.pdf"

        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(600, 800, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas = page.canvas
        val paint = Paint()

        paint.textSize = 24f
        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("RentTrack", 220f, 50f, paint)

        paint.textSize = 14f
        paint.typeface = Typeface.DEFAULT
        canvas.drawText("Payment Receipt", 230f, 80f, paint)

        paint.textSize = 12f
        canvas.drawText("Tenant: ${tenant.name}", 50f, 130f, paint)
        canvas.drawText("Bill Date: ${rentDate}", 50f, 160f, paint)
        canvas.drawText("Receipt No: ${receiptNumber}", 50f, 190f, paint)

        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("Description", 50f, 230f, paint)
        canvas.drawText("Amount", 400f, 230f, paint)

        paint.typeface = Typeface.DEFAULT
        canvas.drawText("Paid Amount", 50f, 290f, paint)
        canvas.drawText("₹$amount", 400f, 290f, paint)

        canvas.drawText("Discount", 50f, 320f, paint)
        canvas.drawText("₹0", 400f, 320f, paint)

        canvas.drawText("Net", 50f, 350f, paint)
        canvas.drawText("₹$amount", 400f, 350f, paint)

        paint.typeface = Typeface.DEFAULT_BOLD
        canvas.drawText("Remaining Amount", 50f, 400f, paint)
        canvas.drawText("₹${tenant.monthlyRent?.minus(amount.toFloat())}", 400f, 400f, paint)

        canvas.drawText("Mode: CASH", 50f, 450f, paint)
        canvas.drawText("Collected By: RentTrack", 50f, 480f, paint)

        paint.textSize = 10f
        paint.typeface = Typeface.MONOSPACE
        canvas.drawText("Generated by RentTrack", 200f, 550f, paint)
        canvas.drawText(
            "This is a computer-generated receipt and does not require any signature/stamp.",
            100f,
            570f,
            paint
        )

        pdfDocument.finishPage(page)

        val file =
            File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), "${fileName}")
        try {
            val outputStream = FileOutputStream(file)
            pdfDocument.writeTo(outputStream)
            pdfDocument.close()
            outputStream.close()
            Log.d("Invoice", "Invoice saved at: ${file.absolutePath}")
            return file
        } catch (e: IOException) {
            e.printStackTrace()
            Log.d("Invoice", "Invoice failed : ${file.absolutePath}")
            return null
        }
    }

    override fun shareInvoice(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.provider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share Invoice"))
    }

}
